### PR TITLE
Add recommended policy ARN for KMS controller

### PR DESCRIPTION
**Pull request by A-Hilaly**
Issue #, if available:

Description of changes:
- Add recommended policy ARN for KMS controller

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
:+1: thanks @A-Hilaly!

**Comment by vijtrip2** [comment]
The release test is failing because kms controller is still using old runtime version.
Merging this PR since the failure is unrelated to this change.

**Pull request merged**
