### PR TITLE
assert tags using acktest.tags

### PR DESCRIPTION
**Pull request by vijtrip2**
Description of changes:
* change tag assertion to use test-infra utility methods

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
Nice, thank you @vijtrip2

**Comment by jaypipes** [comment]
@jljaco @RedbackThomson @A-Hilaly why were tests re-run yesterday for this PR that was merged 8 months ago?

**Comment by RedbackThomson** [comment]
> @jljaco @RedbackThomson @A-Hilaly why were tests re-run yesterday for this PR that was merged 8 months ago?

🤷🏼‍♂️  <-- My best guess

**Comment by RedbackThomson** [comment]
> @jljaco @RedbackThomson @A-Hilaly why were tests re-run yesterday for this PR that was merged 8 months ago?

Oh so I ran a random ProwJob in the cluster just to make sure it was working. It was something that was lying around on my machine, I didn't pay too much attention to what PR was behind it. Guess you found it out

**Comment by jaypipes** [comment]
> > @jljaco @RedbackThomson @A-Hilaly why were tests re-run yesterday for this PR that was merged 8 months ago?
> 
> Oh so I ran a random ProwJob in the cluster just to make sure it was working. It was something that was lying around on my machine, I didn't pay too much attention to what PR was behind it. Guess you found it out

ahhh, gotcha :) figured it was something to do with the testing you were all doing on the Prow upgrade... now I know! thanks!

**Pull request merged**
